// Generated by scripts/sync-atlassian-tokens.mjs from @atlaskit/tokens@20.4.1 (Apache-2.0).
// Do not edit by hand. Run `yarn sync-tokens` to regenerate.

import type { ColorToken } from './colors.generated';

/** Atlassian's Blue ramp, keyed by palette step. Used as the lightness profile for brand ramps. */
export const atlassianBlueRamp = {
  '100': '#E9F2FE',
  '200': '#CFE1FD',
  '250': '#ADCBFB',
  '300': '#8FB8F6',
  '400': '#669DF1',
  '500': '#4688EC',
  '600': '#357DE8',
  '700': '#1868DB',
  '800': '#1558BC',
  '850': '#144794',
  '900': '#123263',
  '1000': '#1C2B42',
} as const;

export type BrandStep = keyof typeof atlassianBlueRamp;

/** Color tokens that use a brand (Blue) palette step, per mode. */
export const atlassianBrandTokens: Record<
  'light' | 'dark',
  Partial<Record<ColorToken, BrandStep>>
> = {
  light: {
    'color.background.selected': '100',
    'color.background.selected.hovered': '200',
    'color.background.selected.pressed': '300',
    'color.background.selected.bold': '700',
    'color.background.selected.bold.hovered': '800',
    'color.background.selected.bold.pressed': '900',
    'color.background.brand.subtlest': '100',
    'color.background.brand.subtlest.hovered': '200',
    'color.background.brand.subtlest.pressed': '250',
    'color.background.brand.bold': '700',
    'color.background.brand.bold.hovered': '800',
    'color.background.brand.bold.pressed': '850',
    'color.background.brand.boldest': '1000',
    'color.background.brand.boldest.hovered': '900',
    'color.background.brand.boldest.pressed': '850',
    'color.border.focused': '500',
    'color.border.selected': '700',
    'color.border.brand': '700',
    'color.text.selected': '700',
    'color.text.brand': '700',
    'color.icon.selected': '700',
    'color.icon.brand': '700',
    'color.link': '700',
    'color.link.pressed': '800',
  },
  dark: {
    'color.background.selected': '1000',
    'color.background.selected.hovered': '900',
    'color.background.selected.pressed': '800',
    'color.background.selected.bold': '400',
    'color.background.selected.bold.hovered': '300',
    'color.background.selected.bold.pressed': '200',
    'color.background.brand.subtlest': '1000',
    'color.background.brand.subtlest.hovered': '900',
    'color.background.brand.subtlest.pressed': '850',
    'color.background.brand.bold': '400',
    'color.background.brand.bold.hovered': '300',
    'color.background.brand.bold.pressed': '250',
    'color.background.brand.boldest': '100',
    'color.background.brand.boldest.hovered': '200',
    'color.background.brand.boldest.pressed': '250',
    'color.border.focused': '300',
    'color.border.selected': '400',
    'color.border.brand': '400',
    'color.text.selected': '400',
    'color.text.brand': '400',
    'color.icon.selected': '400',
    'color.icon.brand': '400',
    'color.link': '400',
    'color.link.pressed': '300',
  },
};
