// Generated by scripts/sync-atlassian-tokens.mjs from @atlaskit/tokens@20.4.1 (Apache-2.0).
// Do not edit by hand. Run `yarn sync-tokens` to regenerate.

export const atlassianRadius = {
  xsmall: 2,
  small: 4,
  medium: 6,
  large: 8,
  xlarge: 12,
  xxlarge: 16,
  full: 9999,
} as const;

export const atlassianBorderWidth = {
  default: 1,
  selected: 2,
  focused: 2,
} as const;
