// Generated by scripts/sync-atlassian-tokens.mjs from @atlaskit/tokens@20.4.1 (Apache-2.0).
// Do not edit by hand. Run `yarn sync-tokens` to regenerate.

export const atlassianSpace = {
  '0': 0,
  '100': 8,
  '150': 12,
  '200': 16,
  '250': 20,
  '300': 24,
  '400': 32,
  '500': 40,
  '600': 48,
  '800': 64,
  '1000': 80,
  '025': 2,
  '050': 4,
  '075': 6,
  'negative.025': -2,
  'negative.050': -4,
  'negative.075': -6,
  'negative.100': -8,
  'negative.150': -12,
  'negative.200': -16,
  'negative.250': -20,
  'negative.300': -24,
  'negative.400': -32,
} as const;
