// Generated by scripts/sync-atlassian-tokens.mjs from @atlaskit/tokens@20.4.1 (Apache-2.0).
// Do not edit by hand. Run `yarn sync-tokens` to regenerate.

export const atlassianTextStyles = {
  'heading.xxlarge': {
    fontWeight: 653,
    fontSize: 32,
    lineHeight: 36,
  },
  'heading.xlarge': {
    fontWeight: 653,
    fontSize: 28,
    lineHeight: 32,
  },
  'heading.large': {
    fontWeight: 653,
    fontSize: 24,
    lineHeight: 28,
  },
  'heading.medium': {
    fontWeight: 653,
    fontSize: 20,
    lineHeight: 24,
  },
  'heading.small': {
    fontWeight: 653,
    fontSize: 16,
    lineHeight: 20,
  },
  'heading.xsmall': {
    fontWeight: 653,
    fontSize: 14,
    lineHeight: 20,
  },
  'heading.xxsmall': {
    fontWeight: 653,
    fontSize: 12,
    lineHeight: 16,
  },
  'body.large': {
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 24,
  },
  body: {
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 20,
  },
  'body.small': {
    fontWeight: 400,
    fontSize: 12,
    lineHeight: 16,
  },
  'metric.large': {
    fontWeight: 653,
    fontSize: 28,
    lineHeight: 32,
  },
  'metric.medium': {
    fontWeight: 653,
    fontSize: 24,
    lineHeight: 28,
  },
  'metric.small': {
    fontWeight: 653,
    fontSize: 16,
    lineHeight: 20,
  },
} as const;

/** CSS font-family stacks. Native apps fall back to the system font unless a theme sets one. */
export const atlassianFontFamilies = {
  heading:
    '"Atlassian Sans", ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  body: '"Atlassian Sans", ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  code: '"Atlassian Mono", ui-monospace, Menlo, "Segoe UI Mono", "Ubuntu Mono", monospace',
  'brand.heading':
    '"Charlie Display", ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
  'brand.body':
    '"Charlie Text", ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, "Helvetica Neue", sans-serif',
} as const;
